### ISSUE TITLE
Requirements run actions

### ISSUE THREAD

**Issue by BadSr92** [kejonaMC/CrossplatForms#140] opened 2022-12-29 23:19 UTC
### What feature do you want to see added?

Add the requirement run actions option, whose function is for the player to meet the requirement to execute the button actions, something like the following.

    requirement_run_actions: #option
        1: #Requirement Name
          placeholder: '%player_empty_slots%' #placeholder 
          should_give: '5' #Value returned by the placeholder to fulfill the requirement
 
And that several requirements can be set and that at least one or all of them must be met

### Are there any alternatives?

None

**Comment by Konicai** [comment] 2023-01-11 06:16
Duplicate of #63 - thanks for the example though

**Closed by Konicai** 2023-01-11 06:16 UTC
