### ISSUE TITLE
Separate Bedrock forms into separate yaml files

### ISSUE THREAD

**Issue by GamingDestiny** [kejonaMC/CrossplatForms#113] opened 2022-08-13 00:41 UTC
### What feature do you want to see added?

Similar to how plugins like DeluxeMenus and ShopGUI+ do it, have each form (or menu for Java players) be in a separate yaml file. Example directory: Files/plugins/CrossplatForms/bedrock-forms/spawn-menu.yml or Files/plugins/CrossplatForms/java-menus/warps.yml

### Are there any alternatives?

As mentioned above, deluxemenus and shopgui have their menus separated, but those aren't designed for Bedrock edition

**Comment by Konicai** [comment] 2022-08-13 00:42
Duplicate of https://github.com/kejonaMC/CrossplatForms/issues/100

Thank you though :)

**Comment by GamingDestiny** [comment] 2022-08-13 00:42
Oh, sorry about that...

**Closed by Konicai** 2022-08-13 00:42 UTC
