### ISSUE TITLE
[Feature Request] Buttons Requirements & Conditions Support

### ISSUE THREAD

**Issue by DJelly4K** [kejonaMC/CrossplatForms#103] opened 2022-07-17 14:17 UTC
### What feature do you want to see added?

like deluxemenus
https://wiki.helpch.at/clips-plugins/deluxemenus/options-and-configurations/requirements

### Are there any alternatives?

no

**Comment by Konicai** [comment] 2022-07-17 15:54
Duplicate of #63 and #68

**Closed** 2022-07-20 06:10 UTC
